### ISSUE TITLE
Actualizar readme para requisitos de plataforma y guias de instalacion rapida

### ISSUE THREAD

**Issue by ivanchenoweth** [cayi/dnc#2]

**Comment by ivanchenoweth** [comment]
Requisitos plataforma 
Tener instalado en forma nativa o virtual sobre el fuente
* PHP Ver>7.3
* composer
* apache 2.0 ?????
* mariadb >10.3 | MySQL version: 5.6.34 

Instalacion y configuracion:
1) copiar el archivo .env

**Comment by ivanchenoweth** [comment]
Falta mergear a main, no me deja hacer push, por problema de permisos

**Comment by ivanchenoweth** [comment]
Hay que copiar esto al readme del main, no se esta dejando porque no tengo permisos

**Comment by ivanchenoweth** [comment]
Ya se puede cerrar

**Comment by cayi** [comment]
Ya le di copy paste, se recorre hacia abajo el anteruior
