### ISSUE TITLE
Error SQLSTATE tabla no encontrada al Importar Usuarios 

### ISSUE THREAD

**Issue by ivanchenoweth** [cayi/dnc#5]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dnc_db.evaluados' doesn't exist
![image](https://user-images.githubusercontent.com/284874/149033035-486e5640-1c69-4efc-9c7c-727cbb508d3a.png)

![image](https://user-images.githubusercontent.com/284874/149033008-b45ea201-2165-4091-8cbe-f393b32203bd.png)

**Comment by cayi** [comment]
Ivab

A mi si me sube el archivo de usuarios, falto correr el paso:
php artisan migrate:fresh --seed
