### ISSUE TITLE
No tengo permisos 

### ISSUE THREAD

**Issue by ivanchenoweth** [cayi/dnc#6]
$ git push origin fix-guia-instalacion-requisitos 
remote: Permission to cayi/dnc.git denied to ivanchenoweth.
fatal: unable to access 'https://github.com/cayi/dnc.git/': The requested URL returned error: 403

**Comment by ivanchenoweth** [comment]
No tengo permisos en git para editar Labels, Assignees, projects, milestone etc.

**Comment by cayi** [comment]
Asi es, debo invitarte como colaborador, el hecho de ser publico queda como "read only", segun yo ya te envie una invitación para colaborar en este proyecto. Me avisas.
