### ISSUE TITLE
Error 404 not found, en la opcion de reportes

### ISSUE THREAD

**Issue by ivanchenoweth** [cayi/dnc#7]
![image](https://user-images.githubusercontent.com/284874/149033512-4c290101-d8da-48bc-af95-22e0959bb051.png)

**Comment by cayi** [comment]
Es correcto, aun NO se implementan las opciones de Reportes, no me han dicho los reportes que se requieren para el DNC, le voy a poner una leyenda de que esta en proceso.

**Comment by ivanchenoweth** [comment]
se puede carrar
